export const authConstant={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL'
};
export const allServices={
    SERVICE_REQUEST:'SERVICE_REQUEST',
    SERVICE_SUCCESS:'SERVICE_SUCCESS',
    SERVICE_FAIL:'SERVICE_FAIL'
};
export const Searching={
    SEARCH_REQUEST:'SEARCH_REQUEST',
    SEARCH_SUCCESS:'SEARCH_SUCCESS',
    SEARCH_FAIL:'SEARCH_FAIL'
};
export const Signup={
SINGUP_REQUEST:'SIGN_REQUEST',
SINGUP_SUCCESS:'SIGNUP_SUCCESS',
SINGUP_FAIL:'SIGNUP_FIAL'
};
export const Passenger={
    PASSENGER_REQUEST:'PASSENGER_REQUEST',
    PASSENGER_SUCCESS:'PASSENGER_SUCCESS',
    PASSENGER_FAILIURE:'PASSENGER_FAILIURE',
    SHOW_PASSENGER_LIST:'SHOW_PASSENGER_LIST',
    SHOW_PASSENGER_LIST_SUCCESS:'SHOW_PASSENGER_LIST_SUCCESS',
    SHOW_PASSENGER_LIST_FAILIURE:'SHOW_PASSENGER_LIST_FAILIURE',
    PASSENGER_ACTIVATE:'PASSENGER_ACTIVATE',
    PASSENGER_ACTIVATE_SUCCESS:'PASSENGER_ACTIVATE_SUCCESS',
    PASSENGER_ACTIVATE_FAILIURE:'PASSENGER_ACTIVATE_FAILIURE',
    PASSENGER_DEACTIVATE:'PASSENGER_DEACTIVATE',
    PASSENGER_DEACTIVATE_SUCCESS:'PASSENGER_DEACTIVATE_SUCCESS',
    PASSENGER_DEACTIVATE_FAILIURE:'PASSENGER_DEACTIVATE_FAILIURE'
}
export const Booking={
    BOOKING_REQUEST:'BOOKING_REQUEST',
    BOOKING_SUCCESS:'BOOKING_SUCCESS',
    BOOKING_FAILIURE:'BOOKING_FAILIURE',
    SHOW_BOOKING_REQUEST:'SHOW_BOOKING_REQUEST',
    SHOW_BOOKING_SUCCESS:'SHOW_BOOKING_SUCCESS',
    SHOW_BOOKING_FAILIURE:'SHOW_BOOKING_FAILIURE',
    GET_BOOKING_INFO:'GET_BOOKING_INFO',
    GET_BOOKING_INFO_SUCCESS:'GET_BOOKING_INFO_SUCCESS',
    GET_BOOKING_INFO_FAILIURE:"GET_BOOKING_INFO_FAILIURE",
    BOOKING_ACTIVATE:'BOOKING_ACTIVATE',
    BOOKING_ACTIVATE_SUCCESS:'BOOKING_ACTIVATE_SUCCESS',
    BOOKING_ACTIVATE_FAILIURE:'BOOKING_ACTIVATE_FAILIURE',
    BOOKING_DEACTIVATE:'BOOKING_DEACTIVATE',
    BOOKING_DEACTIVATE_SUCCESS:'BOOKING_DEACTIVATE_SUCCESS',
    BOOKING_DEACTIVATE_FAILIURE:'BOOKING_DEACTIVATE_FAILIURE'
}
export const Vehicle={
    SAVE_VEHICLE:'SAVE_VEHICLE',
    SAVE_VEHICLE_SUCCESS:'SAVE_VEHICLE_SUCCESS',
    SAVE_VEHICLE_FAILIURE:'SAVE_VEHICLE_FAILIURE',
    GET_VEHICLES:'GET_VEHICLES',
    GET_VEHICLES_SUCCESS:'GET_VEHICLES_SUCCESS',
    GET_VEHICLES_FAILIURE:'GET_VEHICLES_FAILIURE',
    GET_VEHICLE:'GET_VEHICLE',
    GET_VEHICLE_SUCCESS:'GET_VEHICLE_SUCCESS',
    GET_VEHICLE_FAILIURE:'GET_VEHICLE_FAILIURE',
    VEHICLE_ACTIVATE:'VEHICLE_ACTIVATE',
    VEHICLE_ACTIVATE_SUCCESS:'VEHICLE_ACTIVATE_SUCCESS',
    VEHICLE_ACTIVATE_FAILIURE:'VEHICLE_ACTIVATE_FAILIURE',
    VEHICLE_DEACTIVATE:'VEHICLE_DEACTIVATE',
    VEHICLE_DEACTIVATE_SUCCESS:'VEHICLE_DEACTIVATE_SUCCESS',
    VEHICLE_DEACTIVATE_FAILIURE:'VEHICLE_DEACTIVATE_FAILIURE'
}